name: SneakerSpace
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  image_picker: ^0.8.3+2
  http: ^1.2.0
  url_launcher: ^6.0.9
  webview_flutter: ^4.8.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  speech_to_text: ^7.0.0
  audioplayers: ^5.2.1
  get_storage: ^2.1.1
  video_player: ^2.9.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
  - assets/adidas.png
  - assets/default_profile_picture.png
  - assets/nike.png
  - assets/puma.png
  - assets/reebok.png
  - assets/SneakerSpace.png
  - assets/Jordan-1-High-OG-Travis-Scott-x-Fragment-1.png
  - assets/af1peaceminusone.png
  - assets/ajhigh.png
  - assets/ajlow.png
  - assets/nb530.png
  - assets/nmdr1.png
  - assets/rbcls.png
  - assets/SambaOG.png
  - assets/superstar.png
  - assets/converse.png
  - assets/new_balance.png
  - assets/asics.png
  - assets/fila.png
  - assets/la-stravaganza.mp3
  - assets/background.mp3
  - assets/ROSÉ_BrunoMars-APT.mp3