// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNr8yQwl-tvyt2SO5fuACVwk5sFOMCcXE',
    appId: '1:6711667658:web:dbaf522a5e90ee804dfd33',
    messagingSenderId: '6711667658',
    projectId: 'ventela-barabai',
    authDomain: 'ventela-barabai.firebaseapp.com',
    storageBucket: 'ventela-barabai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rkTVUFzeynwa2Wk-m-hxLWu44D1Qr2U',
    appId: '1:6711667658:android:dda0c4ad0674ff554dfd33',
    messagingSenderId: '6711667658',
    projectId: 'ventela-barabai',
    storageBucket: 'ventela-barabai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--t5x5kkMk9Rj8JCbPyp8i1Bi2UVNNlk',
    appId: '1:6711667658:ios:95cd7fb21e821cb14dfd33',
    messagingSenderId: '6711667658',
    projectId: 'ventela-barabai',
    storageBucket: 'ventela-barabai.firebasestorage.app',
    iosBundleId: 'com.example.barabai',
  );
}
